---
title: "Powerlifting myths"
author: "Anna Duan"
date: "8/19/2021"
output: 
  html_document:
    keep_md: true
    toc: true
    theme: cosmo
    toc_float: true
    code_folding: hide
---

Among powerlifters, there are many tropes and debates about our sport.
```{r SetUp, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE, results='hide'}
#Reload
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(scipen=1000000000)
library(knitr)
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(dplyr)
library(viridis)
library(mapview)
library(lubridate)
library(grid)
library(gridExtra)


root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")


plotTheme <- function(base_size = 12, title_size = 16) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = title_size, colour = "black"), 
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

#Read file
powerlifting <- read_csv("/Users/annaduan/Documents/dataviz2021/Powerlifting/openpowerlifting2021.csv") %>%
  filter(MeetCountry == "USA")
PL <- powerlifting %>%
  drop_na(Wilks, TotalKg, Age, Best3SquatKg, Best3BenchKg, Best3DeadliftKg)

#  weight categories
PL <-
  PL %>%
  mutate(Weight.cat = case_when(
                  BodyweightKg >= 0 & BodyweightKg < 50  ~ "50kg",
                  BodyweightKg >= 50 & BodyweightKg < 55  ~ "55kg",
                  BodyweightKg >= 55 & BodyweightKg < 60  ~ "60kg",
                  BodyweightKg >= 60 & BodyweightKg < 65  ~ "65kg",
                  BodyweightKg >= 65 & BodyweightKg < 70  ~ "70kg",
                  BodyweightKg >= 70 & BodyweightKg < 75  ~ "75kg",
                  BodyweightKg >= 75 & BodyweightKg < 80  ~ "80kg",
                  BodyweightKg >= 80 & BodyweightKg < 85  ~ "85kg",
                  BodyweightKg >= 85 & BodyweightKg < 90  ~ "90kg",
                  BodyweightKg >= 90 & BodyweightKg < 95  ~ "95kg",
                  BodyweightKg >= 95 & BodyweightKg < 100  ~ "100kg",
                  BodyweightKg >= 100 & BodyweightKg < 105  ~ "105kg",
                  BodyweightKg >= 105 & BodyweightKg < 110  ~ "110kg",
                  BodyweightKg >= 110 & BodyweightKg < 115  ~ "115kg",
                  BodyweightKg >= 115          ~ "120+ kg")) %>%
    mutate(Weight.cat = fct_relevel(Weight.cat, 
           "50kg", "55kg", "60kg", "65kg", "70kg", "75kg", "80kg","85kg","90kg","95kg","100kg","105kg","110kg","115kg"))

#SBD
SBD <- PL %>%
  dplyr::select(Best3BenchKg, Best3DeadliftKg, Best3SquatKg)

#early phases

PL_1964 <-  PL %>%
subset(.,
     Date >= as.POSIXct('1964-09-05') &
     Date <= as.POSIXct('1984-09-05')
     )  %>%
 #   filter(Sex == "M") %>%
  mutate(Period = "1964 - 1984")
  
SBD_1964 <-
 PL_1964 %>%
    select(Best3BenchKg, Best3SquatKg, Best3DeadliftKg) %>%
  rename(Bench_64 = Best3BenchKg,
         Squat_64 = Best3SquatKg,
         Deadlift_64 = Best3DeadliftKg) %>%
  gather(Variable, Value)

#recent years

PL_2000 <-  PL %>%
subset(.,
     Date >= as.POSIXct('2000-09-05') &
     Date <= as.POSIXct('2020-09-05')
     )  %>%
  #  filter(Sex == "M") %>%
    mutate(Period = "2000 - 2020")


SBD_2000 <- 
  PL_2000 %>%
    select(Best3BenchKg, Best3SquatKg, Best3DeadliftKg) %>%
  rename(Bench_00 = Best3BenchKg,
         Squat_00 = Best3SquatKg,
         Deadlift_00 = Best3DeadliftKg) %>%
  gather(Variable, Value)

PL_both <-
  full_join(PL_1964, PL_2000)

SBD_Compare <- 
  full_join(SBD_1964, SBD_2000)
```

```{r exploring strength distributions, cache=TRUE, message=FALSE, warning=FALSE, include=TRUE}

grid.arrange(  
  
  ggplot(PL, aes(x=Wilks)) +
  geom_histogram() +
  labs(title = "Wilks") +
  plotTheme(), 
  
  ggplot(PL, aes(x=BodyweightKg)) +
  geom_histogram() +
  labs(title = "Bodyweight") +
  plotTheme(), 
  
  ggplot(PL, aes(x=Age)) +
  geom_histogram() +
  labs(title = "Age") +
  plotTheme(), 
  
  ggplot(PL, aes(x=Best3DeadliftKg)) +
  geom_histogram() +
  labs(title = "Deadlift") +
  plotTheme(), 
  
  ggplot(PL, aes(x=Best3SquatKg)) +
  geom_histogram() +
  labs(title = "Squat") +
  plotTheme(),
  
  ggplot(PL, aes(x=Best3BenchKg)) +
  geom_histogram() +
  labs(title = "Bench") +
  plotTheme(),
  
  ncol=3)



#all records
SBD %>%
  gather(Variable, Value) %>%
  ggplot() +
  stat_density(aes(x=Value, fill = Variable, alpha = 0.4)) +
  stat_density(aes(x=Value, fill = Variable, alpha = 0.4)) +
  labs(title = "Squat, Bench, and Deadlift Records: 1964 - 2021", subtitle = "in Kilograms; 1kg = 2.2lbs") +
  plotTheme()
```
 
Powerlifting averages have slightly decreased since the early days despite increases in sports science, equipment, and knowledge. What happened?
```{r exploring strength over time, cache=TRUE, message=FALSE, warning=FALSE, include=TRUE}
#calculate mean weights for each lift during each period
means_2000 <- PL_2000 %>%
  summarize(mean_squat=mean(Best3SquatKg),
            mean_bench=mean(Best3BenchKg),
            mean_dead=mean(Best3DeadliftKg))

  
means_1964 <- PL_1964 %>%
  summarize(mean_squat=mean(Best3SquatKg),
            mean_bench=mean(Best3BenchKg),
            mean_dead=mean(Best3DeadliftKg))



grid.arrange(
  #1964-1984
  SBD_1964 %>%
  ggplot() +
  stat_density(aes(x=Value, fill = Variable, alpha = 0.4), colour = "transparent") +
    xlim(0, 600) +
     geom_vline(data = means_1964, aes(xintercept = mean_squat), size=1.5, color="blue", size = 1.5) +
     geom_vline(data = means_1964, aes(xintercept = mean_bench), size=1.5, color="red", size = 1.5) +
     geom_vline(data = means_1964, aes(xintercept = mean_dead), size=1.5, color="green", size = 1.5) +
  labs(title = "Squat, Bench, and Deadlift Records: 1964 - 1984", subtitle = "in Kilograms; 1kg = 2.2lbs") +
  plotTheme(),

#2000-2020
SBD_2000 %>%
  ggplot() +
  stat_density(aes(x=Value, fill = Variable, alpha = 0.4), colour = "transparent") +
      xlim(0, 600) +
     geom_vline(data = means_2000, aes(xintercept = mean_squat), size=1.5, color="blue", size = 1.5) +      geom_vline(data = means_2000, aes(xintercept = mean_bench), size=1.5, color="red", size = 1.5) +
    geom_vline(data = means_2000, aes(xintercept = mean_dead), size=1.5, color="green", size = 1.5) +
  labs(title = "Squat, Bench, and Deadlift Records: 2000 - 2020", subtitle = "in Kilograms; 1kg = 2.2lbs") +
  plotTheme(),
ncol = 1)





# SBD_Compare %>%
#   filter(Value < 410) %>%
#   ggplot() +
#   stat_density(aes(colour = Variable, x=Value), fill = "transparent") +
#   scale_colour_manual(values =c("purple", "lavender", "orange", "yellow", "forest green", "light green")) +
#     geom_vline(data = means_2000, aes(xintercept = mean_squat), size=1.5, color="forest green", size = 1.5) +
#     geom_vline(data = means_2000, aes(xintercept = mean_bench), size=1.5, color="purple", size = 1.5) +
#     geom_vline(data = means_2000, aes(xintercept = mean_dead), size=1.5, color="orange", size = 1.5) +
#     geom_vline(data = means_1964, aes(xintercept = mean_squat), size=1.5, color="light green", size = 1.5) +
#     geom_vline(data = means_1964, aes(xintercept = mean_bench), size=1.5, color="lavender", size = 1.5) +
#     geom_vline(data = means_1964, aes(xintercept = mean_dead), size=1.5, color="yellow", size = 1.5) +
#   labs(title = "Squat, Bench, and Deadlift Records: 2000 - 2020", subtitle = "in Kilograms; 1kg = 2.2lbs; Outliers Omitted") +
#   plotTheme() 


```


```{r Exploring weight, sex and strength, cache=TRUE, message=FALSE, warning=FALSE, include=TRUE}
Wilks.Summary <- PL %>%
  filter(AgeClass == "24-34") %>%
  dplyr::select(Weight.cat, AgeClass, Best3SquatKg, Best3BenchKg, Best3DeadliftKg, TotalKg, Wilks, Sex) %>%
    group_by(Weight.cat, Sex) %>%
    summarize(Squat = mean(Best3SquatKg, na.rm = T),
              Bench = mean(Best3BenchKg, na.rm = T),
              Deadlift = mean(Best3DeadliftKg, na.rm = T),
              TotalAvg = mean(TotalKg, na.rm = T),
              WilksAvg = mean(Wilks, na.rm = T))

kable(Wilks.Summary) %>%
  kable_styling() %>%
  footnote(general_title = "\n",
           general = "Weight, Sex and PL Outcomes")

Wilks.Summary %>%
  unite(Weight.cat.Sex, Weight.cat, Sex, sep = ": ", remove = T) %>%
  gather(Variable, Value, -Weight.cat.Sex) %>%
  mutate(Value = round(Value, 2)) %>%
  spread(Weight.cat.Sex, Value) %>%
  kable() %>%
    kable_styling() %>%
    footnote(general_title = "\n",
             general = "Weight, Sex and PL Outcomes 2")

Wilks.Summary %>%
  gather(Variable, Value, -Weight.cat, -Sex) %>%
  ggplot(aes(Weight.cat, Value, fill = Sex)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~Variable, scales = "free", ncol=3) +
    scale_fill_manual(values = c("blue", "pink", "green")) +
    labs(title = "Weight Lifted Across Weight Classes and Sex") +
    plotTheme() + theme(legend.position="bottom")


```

```{r drugs, cache=TRUE, message=FALSE, warning=FALSE, include=TRUE}
PED.Summary <- PL %>%
  dplyr::select(Weight.cat, AgeClass, Best3SquatKg, Best3BenchKg, Best3DeadliftKg, TotalKg, Wilks, Sex, Tested) %>%
    group_by(Tested, Weight.cat) %>%
    summarize(Squat = mean(Best3SquatKg, na.rm = T),
              Bench = mean(Best3BenchKg, na.rm = T),
              Deadlift = mean(Best3DeadliftKg, na.rm = T),
              TotalAvg = mean(TotalKg, na.rm = T),
              WilksAvg = mean(Wilks, na.rm = T))

PED.Summary %>%
  gather(Variable, Value, -Weight.cat, -Tested) %>%
  ggplot(aes(Weight.cat, Value, fill = Tested)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~Variable, scales = "free", ncol=3) +
    scale_fill_manual(values = c("blue", "pink", "green")) +
    labs(title = "Strength and PED Testing") +
    plotTheme() + theme(legend.position="bottom")
```



